In [9]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pickle

In [16]:
import pathlib

AttributeError: module 'pickle' has no attribute '__version__'

In [11]:
np.__version__

'1.23.2'

In [2]:
import sklearn

In [3]:
sklearn.__version__

'1.1.3'

In [2]:
import fastapi

In [3]:
fastapi.__version__

'0.88.0'

In [4]:
import pydantic

In [5]:
pydantic.__version__

'1.10.2'

In [6]:
import streamlit

In [7]:
streamlit.__version__

'1.13.0'

In [2]:
#readin dataset
dataset = pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
X = dataset.iloc[:, [2,3]].values

In [5]:
X[:5]

array([[   19, 19000],
       [   35, 20000],
       [   26, 43000],
       [   27, 57000],
       [   19, 76000]])

In [6]:
y = dataset.iloc[:, 4].values

In [7]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)

In [9]:
X_test = sc.transform(X_test)

In [10]:
X_train[:5]

array([[ 0.58164944, -0.88670699],
       [-0.60673761,  1.46173768],
       [-0.01254409, -0.5677824 ],
       [-0.60673761,  1.89663484],
       [ 1.37390747, -1.40858358]])

In [11]:
# Fitting K-NN to the Training set
from sklearn.neighbors import KNeighborsClassifier
cl = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
cl.fit(X_train, y_train)

KNeighborsClassifier()

In [12]:
y_pred = cl.predict(X_test)

In [13]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1])

In [14]:
arr = np.array([-0.80480212, 0.50496393]) #(2,)

In [15]:
arr.shape

(2,)

In [16]:
y_pred_1 = cl.predict(arr.reshape(1, -1)) #reshape when you have only one example

In [17]:
y_pred_1

array([0])

### By using pipeline

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [20]:
# Fitting K-NN to the Training set
from sklearn.neighbors import KNeighborsClassifier
cl = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)

In [21]:
from sklearn.pipeline import Pipeline

pipe = Pipeline([("sc", sc),
                ("classifier", cl)])

In [22]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('sc', StandardScaler()),
                ('classifier', KNeighborsClassifier())])

In [23]:
y_pred2 = pipe.predict(X_test)

In [24]:
y_pred2

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1])

In [25]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
ac2 = accuracy_score(y_test, y_pred2)

In [26]:
ac2

0.93

In [27]:
ac1 = accuracy_score(y_test, y_pred)

In [28]:
ac1

0.93

In [29]:
#displaying pipeline
#https://scikit-learn.org/stable/auto_examples/miscellaneous/plot_pipeline_display.html

In [30]:
with open('trained_pipeline-0.1.0.pkl','wb') as f:
    pickle.dump(pipe, f)

### Read_in

In [31]:
from pathlib import Path
import pickle

In [32]:
BASE_DIR = Path().resolve(strict=True).parent

In [33]:
BASE_DIR #yek folder balatar

PosixPath('/home/abaygi/Documents/Educational/FastApi_projects')

In [34]:
__version__ = "0.1.0"

In [35]:
f"{BASE_DIR}/trained_pipeline-{__version__}.pkl"

'/home/abaygi/Documents/Educational/FastApi_projects/trained_pipeline-0.1.0.pkl'

In [36]:



#with open(f"{BASE_DIR}/trained_pipeline-{__version__}.pkl", "rb") as f:
    #model = pickle.load(f)

In [37]:

with open(f"trained_pipeline-0.1.0.pkl", "rb") as f:
    model = pickle.load(f)

In [38]:


def predict_pipeline(arr):
    pred = model.predict(arr)
    return pred

In [39]:
X[:1].shape

(1, 2)

In [58]:
X_test[:8]

array([[    30,  87000],
       [    38,  50000],
       [    35,  75000],
       [    30,  79000],
       [    35,  50000],
       [    27,  20000],
       [    31,  15000],
       [    36, 144000]])

In [41]:
per = predict_pipeline(X_test[:20])

In [42]:
per

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0])

In [43]:
BASE_DIR1 = Path().resolve(strict=True)

In [44]:
BASE_DIR1

PosixPath('/home/abaygi/Documents/Educational/FastApi_projects/social_netwrok_ads')

In [45]:
predict_pipeline([[ 30, 87000]])

array([0])

In [46]:
predict_pipeline([[ 30, 87000]])[0]

0

In [47]:
###Itrable problem
arr = np.array([1, 2, 3])

In [49]:
arr[2]

3

In [48]:
for i in arr[2]:
    print(i)

TypeError: 'numpy.int64' object is not iterable

In [54]:
dict(arr[0])

TypeError: 'numpy.int64' object is not iterable

In [55]:
my_dict = {"Zero":arr[0]}

In [56]:
my_dict

{'Zero': 1}

In [51]:
d = dict(name='Alice', age=30)
print(d)

{'name': 'Alice', 'age': 30}


In [52]:
arr = np.array([1, 2, 3])

for idx, el in enumerate(arr):
    print(idx, el)

0 1
1 2
2 3


### How to send post request

copy curl from http://127.0.0.1:8000/docs#/default/home__get and use https://curlconverter.com to convert it to python code. 

In [17]:
import requests, json

In [18]:
ml_model_input = {35, 60000}

In [26]:
headers = {
    'accept': 'application/json',
}

response = requests.get('http://127.0.0.1:8000/', headers=headers)

In [27]:
response.status_code

200

In [20]:
headers = {
        'accept': 'application/json',
        'Content-Type': 'application/json',
    }

In [29]:
import requests

headers = {
    'accept': 'application/json',
    'Content-Type': 'application/json',
}

json_data = {
    'age': 45,
    'salary': 135000,
}

response = requests.post('http://127.0.0.1:8000/predict', headers=headers, json=json_data)

In [30]:
response.text

'{"class_index":1}'